#' Compute ratios of relative barcode abundance between treatments
#'
#' Computes the ratio of relative barcode abundance for each cell line
#' between treatment groups and a control group using posterior samples
#' of barcode fractions obtained from the barmixR model.
#'
#' Posterior samples of barcode composition are derived from the
#' Dirichlet–multinomial component of the model. Relative abundance
#' ratios are calculated for each treatment relative to the control
#' group and summarized using log-transformed values.
#'
#' @param model An object of class \code{\link{barmixR_fit}} returned by \code{\link{barmixRQTR}}
#'   containing:
#'   \itemize{
#'     \item \code{names_cell}: Vector of cell line identifiers.
#'     \item \code{control_group}: Name of the control group.
#'     \item \code{condition_count}: Vector of treatment conditions.
#'     \item \code{n_sam}: Number of posterior samples retained.
#'     \item \code{L}: Number of cell lines.
#'     \item \code{K}: Number of treatment conditions.
#'   }
#'
#' @param sampled_fraction A list of matrices containing posterior
#'   samples of barcode fractions for each treatment condition,
#'   typically generated by \code{ppcBarcodes()}.
#'
#' @param q_up Upper quantile threshold used to remove extreme values
#'   (default: 0.975).
#'
#' @param q_lo Lower quantile threshold used to remove extreme values
#'   (default: 0.025).
#'
#' @return An object of class \code{barmixR_result} containing:
#'   \itemize{
#'     \item \code{plot_ratio_fraction}: A \code{ggplot2} violin plot showing
#'       log-ratios of relative barcode abundance.
#'
#'     \item \code{li_sam_ratio_relative}: A list of matrices containing
#'       computed relative abundance ratios.
#'       
#'     \item \code{type}: Result type ("fraction_ratio"). 
#'   }
#'
#' @importFrom ggplot2 ggplot aes geom_violin facet_wrap geom_hline labs theme
#' @importFrom ggplot2 element_text margin
#' @importFrom dplyr group_by mutate ungroup filter
#'
#' @examples
#' set.seed(1)
#'
#' ## ---------------------------
#' ## Simulate small example data
#' ## ---------------------------
#'
#' # barcode count matrix (4 samples x 5 clones)
#' data_count <- matrix(
#'   sample(1:50, 20, replace = TRUE),
#'   nrow = 4
#' )
#'
#' colnames(data_count) <- paste0("clone", 1:5)
#' rownames(data_count) <- c("DMSO_rep1", "DMSO_rep2",
#'                          "TreatA_rep1", "TreatA_rep2")
#'
#' # treatment labels
#' condition_count <- factor(c("DMSO", "DMSO", "TreatA", "TreatA"))
#'
#' # population size (e.g. tumor volume)
#' V <- c(100, 120, 300, 280)
#'
#' # assemble input
#' data <- list(
#'   data_count = data_count,
#'   condition_count = condition_count,
#'   V = V,
#'   condition_v = condition_count,
#'   cell_line = factor(colnames(data_count))
#' )
#'
#' ## ---------------------------
#' ## Fit model (fast settings)
#' ## ---------------------------
#'
#' fit <- barmixRQTR(
#'   data = data,
#'   time_d = 10,
#'   control = list(
#'     chains = 1,
#'     iter_count = 50,
#'     iter_V = 50,
#'     cores = 1
#'   ),
#'   seed = 123
#' )
#'
#' ## ---------------------------
#' ## Posterior Predictive Checks for Barcode Counts
#' ## ---------------------------
#'
#' ppc <- ppcBarcodes(fit)
#'
#' ## ---------------------------
#' ## Estimate fraction ratios
#' ## ---------------------------
#'
#' ratio_res <- fractionRatio(
#'   model = fit,
#'   sampled_fraction = ppc$sampled_fraction
#' )
#'
#' ## plot
#' ratio_res$plot_ratio_fraction
#'
#' @export
fractionRatio <- function(
    model,
    sampled_fraction,
    q_up = 0.975,
    q_lo = 0.025
) {

  ## ---------- helpers ----------
  .stop_if <- function(cond, msg) {
    if (isTRUE(cond)) stop(msg, call. = FALSE)
  }

  ## ---------- validate inputs ----------
  .stop_if(is.null(model) || !inherits(model, "barmixR_fit"),
           "`model` must be an object of class 'barmixR_fit' returned by `barmixRQTR()`.")

  required_fields <- c("names_cell", "condition_count", "n_sam", "L", "K")
  missing_fields <- setdiff(required_fields, names(model))

  .stop_if(length(missing_fields) > 0,
           paste0("Missing required fields in `model`: ",
                  paste(missing_fields, collapse = ", ")))

  .stop_if(is.null(sampled_fraction) || !is.list(sampled_fraction),
           "`sampled_fraction` must be a list of posterior samples from `ppcBarcodes()`.")

  cell <- unique(model$names_cell)
  condition_count <- as.character(model$condition_count)
  control_group <- model$control_group
  n_sam <- as.integer(model$n_sam)
  L <- as.integer(model$L)
  K <- as.integer(model$K)

  ## ---------- control group ----------
  if (is.null(control_group)) {
    control_group <- unique(condition_count)[1]
    message("`control_group` not specified; using: ", control_group)
  }

  .stop_if(!(control_group %in% condition_count),
           "`control_group` must be present in `condition_count`.")

  ## ---------- replication per cell ----------
  rep_per_cell <- table(model$names_cell)

  ## ---------- compute ratios ----------
  li_sam_ratio_relative <- list()
  ratio_index <- 1

  expmus_ref <- NULL

  for (k in seq_len(K)) {

    expmus <- sampled_fraction[[k]]

    .stop_if(is.null(expmus),
             paste0("Missing sampled fraction matrix for condition index ", k))

    expmus <- as.matrix(expmus)

    ## sum replicates per cell
    expmus_cell <- matrix(0, nrow = nrow(expmus), ncol = L)
    colnames(expmus_cell) <- cell
    for (l in seq_len(L)) {

      start_col <- sum(rep_per_cell[seq_len(l-1)]) + 1
      end_col <- sum(rep_per_cell[seq_len(l)])

      expmus_cell[, l] <- rowSums(
        expmus[, start_col:end_col, drop = FALSE]
      )
    }

    cond_name <- unique(condition_count)[k]

    if (identical(cond_name, control_group)) {
      expmus_ref <- expmus_cell
      next
    }

    .stop_if(is.null(expmus_ref),
             "Control group fractions were not found in `sampled_fraction`.")

    li_sam_ratio_relative[[ratio_index]] <-
      expmus_cell / (expmus_ref + 1e-10)

    ratio_index <- ratio_index + 1
  }

  names(li_sam_ratio_relative) <-
    setdiff(unique(condition_count), control_group)

  ## ---------- prepare data for plotting ----------
  ratio_values <- unlist(li_sam_ratio_relative)

  treat_vec <- rep(names(li_sam_ratio_relative),
                   each = L * n_sam)

  cell_vec <- rep(
    rep(cell, each = n_sam),
    length(li_sam_ratio_relative)
  )

  data_plot <- data.frame(
    p_ratio = log(ratio_values),
    treat = treat_vec,
    cell = cell_vec,
    stringsAsFactors = FALSE
  )

  conditions <- unique(model$condition_count)
  conditions <- conditions[conditions != control_group]

  data_plot$treat <- factor(data_plot$treat, levels = conditions)

  ## ---------- quantile filtering ----------
  data_plot <- dplyr::group_by(data_plot, treat, cell)

  data_plot <- dplyr::mutate(
    data_plot,
    keep = p_ratio >= quantile(p_ratio, q_lo) &
      p_ratio <= quantile(p_ratio, q_up)
  )

  data_plot <- dplyr::filter(data_plot, keep)

  data_plot <- dplyr::ungroup(data_plot)

  ## ---------- plot ----------
  threshold <- 0

  plot_ratio_fraction <-
    ggplot2::ggplot(
      data_plot,
      ggplot2::aes(
        x = factor(cell, levels = unique(cell)),
        y = p_ratio,
        fill = factor(cell, levels = unique(cell))
      )
    ) +
    ggplot2::geom_violin(
      draw_quantiles = c(0.25, 0.5, 0.75),
      scale = "width",
      trim = FALSE
    ) +
    ggplot2::facet_wrap(~ treat) +
    ggplot2::geom_hline(
      yintercept = threshold,
      linetype = "dashed",
      colour = "blue",
      linewidth = 1
    ) +
    ggplot2::labs(
      x = "Cell line",
      y = "Ratio of relative abundances, treatment/DMSO (logₑ)",
      fill = "Cell line"
    ) +
    ggplot2::theme(
      axis.text.x = ggplot2::element_text(face = "bold", size = 18, angle = 45, hjust = 1),
      axis.text.y = ggplot2::element_text(face = "bold", size = 18),
      axis.title.x = ggplot2::element_text(face = "bold", size = 18),
      axis.title.y = ggplot2::element_text(face = "bold", size = 18),
      strip.text = ggplot2::element_text(face = "bold", size = 18),
      plot.margin = ggplot2::margin(20, 20, 40, 40),
      legend.title = ggplot2::element_text(size = 18),
      legend.text = ggplot2::element_text(size = 15)
    )

  ## ---------- return ----------
  out <-list(
    plot_ratio_fraction = plot_ratio_fraction,
    li_sam_ratio_relative = li_sam_ratio_relative,
    type = "fraction_ratio"
  )
  class(out) <- "barmixR_result"
  out
}
