#' Compute ratios of population size between treatments
#'
#' Computes ratios of population size between treatment groups and a
#' control group using posterior samples obtained from the barmixR model.
#'
#' Population size corresponds to tumor volume in \emph{in vivo}
#' experiments or cellular confluency in \emph{in vitro} assays.
#' Posterior samples of population size are obtained from the
#' population model component of \code{barmixRQTR()}, typically using
#' \code{ppcPopulation()}. Ratios are calculated relative to the control
#' group and summarized using log-transformed values.
#'
#' @param model An object of class \code{\link{barmixR_fit}} returned by \code{\link{barmixRQTR}}
#'   containing:
#'   \itemize{
#'     \item \code{condition_v}: Vector of treatment condition labels.
#'     \item \code{K}: Number of treatment conditions.
#'     \item \code{n_sam}: Number of posterior samples retained.
#'     \item \code{in_vivo}: Logical indicating whether population size
#'       corresponds to tumor volume (\emph{in vivo}) or confluency
#'       (\emph{in vitro}).
#'   }
#'
#' @param sampled_elements A named list of posterior samples of
#'   population size (tumor volume in \emph{in vivo} experiments or
#'   confluency in \emph{in vitro} assays), typically generated by
#'   \code{ppcPopulation()}.
#'
#' @param q_up Upper quantile threshold used to remove extreme values
#'   (default: 0.975).
#'
#' @param q_lo Lower quantile threshold used to remove extreme values
#'   (default: 0.025).
#'
#' @param control_group Optional name of the control treatment group.
#'
#' @return An object of class \code{barmixR_result} containing:
#'   \itemize{
#'     \item \code{plot_ratio_population}: A \code{ggplot2} violin plot showing
#'       log-ratios of population size between treatments.
#'
#'     \item \code{merged_data}: Data frame used for visualization.
#'
#'     \item \code{li_sam_ratio_V}: List containing computed population
#'       size ratios.
#'       
#'     \item \code{type}: Result type ("population_ratio"). 
#'   }
#'
#' @importFrom ggplot2 ggplot aes geom_violin geom_hline labs theme
#' @importFrom ggplot2 element_text element_rect margin
#' @importFrom dplyr group_by summarise arrange mutate filter ungroup left_join
#' @importFrom stats ecdf quantile
#'
#' @examples
#' set.seed(1)
#'
#' ## ---------------------------
#' ## Simulate small example data
#' ## ---------------------------
#' 
#' # barcode count matrix (4 samples x 5 clones)
#' data_count <- matrix(
#'   c(
#'     20, 22, 24, 23, 21,   # DMSO_rep1
#'     21, 23, 25, 22, 20,   # DMSO_rep2
#'     26, 25, 22, 20, 18,   # TreatA_rep1
#'     25, 24, 23, 21, 19    # TreatA_rep2
#'   ),
#'   nrow = 4,
#'   byrow = TRUE
#' )
#'
#' colnames(data_count) <- paste0("clone", 1:5)
#' rownames(data_count) <- c("DMSO_rep1", "DMSO_rep2",
#'                          "TreatA_rep1", "TreatA_rep2")
#'
#' # treatment labels
#' condition_count <- factor(c("DMSO", "DMSO", "TreatA", "TreatA"))
#'
#' # population size (e.g. tumor volume)
#' V <- c(300, 280, 100, 120)
#'
#' # assemble input
#' data <- list(
#'   data_count = data_count,
#'   condition_count = condition_count,
#'   V = V,
#'   condition_v = condition_count,
#'   cell_line = factor(colnames(data_count))
#' )
#'
#' ## Fit model (fast settings for example only)
#' ## Note: iteration numbers are intentionally small to ensure the example runs quickly.
#' ## For real analysis, increase iterations (e.g., 10000) and use multiple chains.
#'
#' fit <- barmixRQTR(
#'   data = data,
#'   time_d = 10,
#'   control = list(
#'     chains = 1,
#'     iter_count = 50,
#'     iter_V = 50,
#'     cores = 1
#'   ),
#'   seed = 123
#' )
#' 
#' ## ---------------------------
#' ## Posterior Predictive Check for Population Size
#' ## ---------------------------
#'
#' ppc_pop <- ppcPopulation(fit)
#' 
#' ## ---------------------------
#' ## Estimate ratios of population size
#' ## ---------------------------
#' ratio_pop <- populationRatio(
#'   model = fit,
#'   sampled_elements = ppc_pop$sampled_population
#' )
#'
#' ## plot
#' ratio_pop $plot_ratio_population
#' 
#' @export
populationRatio <- function(
    model,
    sampled_elements,
    q_up = 0.975,
    q_lo = 0.025,
    control_group = NULL
) {

  ## ---------- helpers ----------
  .stop_if <- function(cond, msg) {
    if (isTRUE(cond)) stop(msg, call. = FALSE)
  }

  ## ---------- validate inputs ----------
  .stop_if(is.null(model) || !inherits(model, "barmixR_fit"),
           "`model` must be an object of class 'barmixR_fit' returned by `barmixRQTR()`.")

  required_fields <- c("condition_v", "K", "n_sam", "in_vivo")
  missing_fields <- setdiff(required_fields, names(model))

  .stop_if(length(missing_fields) > 0,
           paste0("Missing required fields in `model`: ",
                  paste(missing_fields, collapse = ", ")))

  .stop_if(is.null(sampled_elements) || !is.list(sampled_elements),
           "`sampled_elements` must be a list of posterior samples from `ppcPopulation()`.")

  ## ---------- extract model parameters ----------
  condition_v <- as.character(model$condition_v)
  K <- as.integer(model$K)
  n_sam <- as.integer(model$n_sam)
  in_vivo <- isTRUE(model$in_vivo)

  conditions <- unique(condition_v)

  names(sampled_elements) <- conditions

  threshold <- 0

  ## ---------- control group ----------
  if (is.null(control_group)) {
    control_group <- conditions[1]
    message("`control_group` not specified; using: ", control_group)
  }

  .stop_if(!(control_group %in% conditions),
           "`control_group` must be present in `condition_v`.")

  ## ---------- compute ratios ----------
  li_sam_ratio_V <- list()
  ratio_index <- 1

  expmus_ref <- NULL

  for (k in seq_len(K)) {

    cond_name <- conditions[k]
    expmus <- sampled_elements[[k]]

    .stop_if(is.null(expmus),
             paste0("Missing sampled elements for condition: ", cond_name))

    if (identical(cond_name, control_group)) {
      expmus_ref <- expmus
      next
    }

    .stop_if(is.null(expmus_ref),
             "Control group samples were not found in `sampled_elements`.")

    li_sam_ratio_V[[ratio_index]] <- expmus / expmus_ref
    ratio_index <- ratio_index + 1
  }

  names(li_sam_ratio_V) <- setdiff(conditions, control_group)

  ## ---------- prepare data ----------
  ratio_values <- unlist(li_sam_ratio_V)

  treat_vec <- rep(names(li_sam_ratio_V), each = n_sam)

  data_ratio_V <- data.frame(
    p_ratio = log(ratio_values),
    treat = treat_vec,
    stringsAsFactors = FALSE
  )

  data_ratio_V$treat <- factor(
    data_ratio_V$treat,
    levels = setdiff(conditions, control_group)
  )

  ## ---------- CDF calculation ----------
  get_cdf_value <- function(x, threshold) {
    stats::ecdf(x)(threshold)
  }

  cdf_data <- dplyr::group_by(data_ratio_V, treat)

  cdf_data <- dplyr::summarise(
    cdf_data,
    CDF = get_cdf_value(p_ratio, threshold)
  )

  cdf_data <- dplyr::arrange(cdf_data, CDF)

  ## ---------- quantile filtering ----------
  filtered_data <- dplyr::group_by(data_ratio_V, treat)

  filtered_data <- dplyr::mutate(
    filtered_data,
    keep = p_ratio >= stats::quantile(p_ratio, q_lo) &
      p_ratio <= stats::quantile(p_ratio, q_up)
  )

  filtered_data <- dplyr::filter(filtered_data, keep)

  filtered_data <- dplyr::ungroup(filtered_data)

  ## ---------- merge ----------
  merged_data <- dplyr::left_join(filtered_data, cdf_data, by = "treat")

  ## ---------- plot ----------
  plot_ratio_v <- ggplot2::ggplot(
    merged_data,
    ggplot2::aes(x = treat, y = p_ratio)
  ) +
    ggplot2::geom_violin(
      draw_quantiles = c(0.25, 0.5, 0.75),
      fill = "deepskyblue",
      alpha = 0.7,
      trim = FALSE
    ) +
    ggplot2::geom_hline(
      yintercept = threshold,
      linetype = "dashed",
      colour = "blue",
      linewidth = 1.5
    ) +
    ggplot2::labs(
      x = "Treatment",
      y = if (in_vivo) {
        "Tumor volume relative to control (logₑ)"
      } else {
        "Confluency relative to control (logₑ)"
      }
    ) +
    ggplot2::theme(
      panel.border = ggplot2::element_rect(
        colour = "black",
        fill = NA,
        linewidth = 2
      ),
      axis.text.x = ggplot2::element_text(
        face = "bold",
        size = 18,
        angle = 45,
        hjust = 1
      ),
      axis.text.y = ggplot2::element_text(face = "bold", size = 18),
      axis.title.x = ggplot2::element_text(face = "bold", size = 18),
      axis.title.y = ggplot2::element_text(face = "bold", size = 18),
      plot.margin = ggplot2::margin(20, 20, 40, 40)
    )

  ## ---------- return ----------
  out <-list(
    plot_ratio_population = plot_ratio_v,
    merged_data = merged_data,
    li_sam_ratio_V = li_sam_ratio_V,
    type = "population_ratio"
  )
  class(out) <- "barmixR_result"
  out
}
