#' Estimate quantitative treatment resistance (QTR)
#'
#' Estimates quantitative treatment resistance (QTR) for each cell line
#' by combining posterior samples of barcode relative abundance and
#' population size ratios derived from the barmixR model.
#'
#' Population size corresponds to tumor volume in \emph{in vivo}
#' experiments or cellular confluency in \emph{in vitro} assays.
#' Treatment resistance is computed from posterior ratios of relative
#' barcode abundance and population size, and summarized across
#' posterior samples.
#'
#' The function computes resistance distributions, cumulative
#' distribution function (CDF) statistics, and summary values for each
#' treatment and cell line.
#'
#' @param model An object of class \code{\link{barmixR_fit}} returned by \code{\link{barmixRQTR}}
#'   containing:
#'   \itemize{
#'     \item \code{names_cell}: Vector of cell line identifiers.
#'     \item \code{n_sam}: Number of posterior samples retained.
#'     \item \code{L}: Number of cell lines.
#'     \item \code{time_d}: Duration of the experiment.
#'   }
#'
#' @param li_sam_ratio_relative A list of matrices containing posterior
#'   ratios of relative barcode abundance, typically generated by
#'   \code{fractionRatio()}.
#'
#' @param li_sam_ratio_V A list of vectors containing posterior ratios
#'   of population size (tumor volume in \emph{in vivo} experiments or
#'   confluency in \emph{in vitro} assays), typically generated by
#'   \code{populationRatio()}.
#'
#' @param q_up Upper quantile threshold used to remove extreme values
#'   (default: 0.975).
#'
#' @param q_lo Lower quantile threshold used to remove extreme values
#'   (default: 0.025).
#'
#' @return An object of class \code{barmixR_result} containing:
#'   \itemize{
#'     \item \code{treatment_resistance}: Violin plot showing posterior
#'       distributions of quantitative treatment resistance (QTR).
#'
#'     \item \code{summary_table}: Data frame summarizing treatment
#'       resistance statistics for each cell line and treatment,
#'       including:
#'       \itemize{
#'         \item \code{cell}: Cell line identifier.
#'         \item \code{treat}: Treatment identifier.
#'         \item \code{mean}: Mean resistance estimate.
#'         \item \code{median}: Median resistance estimate.
#'         \item \code{sd}: Standard deviation of resistance estimates.
#'         \item \code{q25}: First quartile (25th percentile).
#'         \item \code{q75}: Third quartile (75th percentile).
#'         \item \code{lower_whisker}: Lower whisker of the resistance distribution.
#'         \item \code{upper_whisker}: Upper whisker of the resistance distribution.
#'         \item \code{CDF}: Cumulative distribution function value
#'           evaluated at zero resistance.
#'       }
#'    \item \code{type}: Result type ("QTR"). 
#'   }
#'
#' @importFrom ggplot2 ggplot aes geom_violin geom_hline facet_wrap labs theme
#' @importFrom ggplot2 element_text margin
#' @importFrom dplyr group_by summarise mutate filter ungroup
#' @importFrom stats ecdf quantile
#'
#' @examples
#' set.seed(1)
#'
#' ## ---------------------------
#' ## Simulate small example data
#' ## ---------------------------
#'
#' # barcode count matrix (4 samples x 5 clones)
#' data_count <- matrix(
#'   c(
#'     20, 22, 24, 23, 21,   # DMSO_rep1
#'     21, 23, 25, 22, 20,   # DMSO_rep2
#'     26, 25, 22, 20, 18,   # TreatA_rep1
#'     25, 24, 23, 21, 19    # TreatA_rep2
#'   ),
#'   nrow = 4,
#'   byrow = TRUE
#' )
#'
#' colnames(data_count) <- paste0("clone", 1:5)
#' rownames(data_count) <- c("DMSO_rep1", "DMSO_rep2",
#'                          "TreatA_rep1", "TreatA_rep2")
#'
#' # treatment labels
#' condition_count <- factor(c("DMSO", "DMSO", "TreatA", "TreatA"))
#'
#' # population size (e.g. tumor volume)
#' V <- c(300, 280, 100, 120)
#'
#' # assemble input
#' data <- list(
#'   data_count = data_count,
#'   condition_count = condition_count,
#'   V = V,
#'   condition_v = condition_count,
#'   cell_line = factor(colnames(data_count))
#' )
#'
#' ## Fit model (fast settings for example only)
#' ## Note: iteration numbers are intentionally small to ensure the example runs quickly.
#' ## For real analysis, increase iterations (e.g., 10000) and use multiple chains.
#'
#' fit <- barmixRQTR(
#'   data = data,
#'   time_d = 10,
#'   control = list(
#'     chains = 1,
#'     iter_count = 50,
#'     iter_V = 50,
#'     cores = 1
#'   ),
#'   seed = 123
#' )
#' 
#' ## ---------------------------
#' ## Downstream analysis pipeline
#' ## ---------------------------
#'
#' # barcode PPC
#' ppc_bar <- ppcBarcodes(fit)
#'
#' # fraction ratios
#' frac_ratio <- fractionRatio(
#'   model = fit,
#'   sampled_fraction = ppc_bar$sampled_fraction
#' )
#'
#' # population PPC
#' ppc_pop <- ppcPopulation(fit)
#'
#' # population ratios
#' pop_ratio <- populationRatio(
#'   model = fit,
#'    sampled_elements = ppc_pop$sampled_population
#' )
#'
#' ## ---------------------------
#' ## Estimate QTR
#' ## ---------------------------
#'
#' res <- QTRresistance(
#'   model = fit,
#'   li_sam_ratio_relative = frac_ratio$li_sam_ratio_relative,
#'   li_sam_ratio_V = pop_ratio$li_sam_ratio_V
#' )
#'
#' ## visualize resistance
#' res$treatment_resistance
#' 
#' @export
QTRresistance <- function(
    model,
    li_sam_ratio_relative,
    li_sam_ratio_V,
    q_up = 0.975,
    q_lo = 0.025
) {
  
  ## ---------- helpers ----------
  .stop_if <- function(cond, msg) {
    if (isTRUE(cond)) stop(msg, call. = FALSE)
  }
  
  ## ---------- validate inputs ----------
  .stop_if(is.null(model) || !inherits(model, "barmixR_fit"),
           "`model` must be an object of class 'barmixR_fit' returned by `barmixRQTR()`.")
  
  required_fields <- c("names_cell", "n_sam", "L", "time_d")
  missing_fields <- setdiff(required_fields, names(model))
  
  .stop_if(length(missing_fields) > 0,
           paste0("Missing required fields in `model`: ",
                  paste(missing_fields, collapse = ", ")))
  
  .stop_if(is.null(li_sam_ratio_relative) || !is.list(li_sam_ratio_relative),
           "`li_sam_ratio_relative` must be a list of posterior fraction ratios from fractionRatio().")
  
  .stop_if(is.null(li_sam_ratio_V) || !is.list(li_sam_ratio_V),
           "`li_sam_ratio_V` must be a list of posterior population ratios from populationRatio().")
  
  ## ---------- extract model elements ----------
  cell <- unique(model$names_cell)
  n_sam <- as.integer(model$n_sam)
  L <- as.integer(model$L)
  time_d <- as.numeric(model$time_d)
  
  listm <- li_sam_ratio_relative
  listv <- li_sam_ratio_V
  
  ## ---------- compute resistance ----------
  result <- list()
  result_qu <- list()
  
  for (name in intersect(names(listm), names(listv))) {
    
    matrix_val <- listm[[name]]
    vector_val <- listv[[name]]
    
    .stop_if(!is.matrix(matrix_val),
             paste0("`li_sam_ratio_relative[['", name, "']]` must be a matrix."))
    
    .stop_if(!is.numeric(vector_val),
             paste0("`li_sam_ratio_V[['", name, "']]` must be numeric."))
    
    result[[name]] <-
      matrix_val *
      matrix(vector_val,
             nrow = nrow(matrix_val),
             ncol = ncol(matrix_val))
    
    result_qu[[name]] <-
      matrix_val *
      stats::quantile(vector_val, probs = 0.5)
  }
  
  treat_names <- names(result)
  
  ## ---------- combine results ----------
  all_eff <- unlist(result)
  qu_eff <- unlist(result_qu)
  
  treat_vec <- rep(treat_names, each = L * n_sam)
  cell_vec <- rep(rep(cell, each = n_sam), length(treat_names))
  
  data_g <- data.frame(
    all_eff = log(all_eff) / time_d,
    qu_eff = log(qu_eff),
    treat = factor(treat_vec, levels = treat_names),
    cell = factor(cell_vec, levels = cell),
    stringsAsFactors = FALSE
  )
  
  ## ---------- CDF calculation ----------
  get_cdf_value <- function(x, threshold) {
    stats::ecdf(x)(threshold)
  }
  
  cdf_data <- dplyr::group_by(data_g, cell, treat)
  
  cdf_data <- dplyr::summarise(
    cdf_data,
    CDF = round(get_cdf_value(all_eff, 0), 2),
    .groups = "drop"
  )
  
  ## ---------- quantile filtering ----------
  filtered_data1 <- dplyr::group_by(data_g, cell, treat)
  
  filtered_data1 <- dplyr::mutate(
    filtered_data1,
    keep = all_eff >= stats::quantile(all_eff, q_lo) &
      all_eff <= stats::quantile(all_eff, q_up)
  )
  
  filtered_data1 <- dplyr::filter(filtered_data1, keep)
  
  filtered_data1 <- dplyr::ungroup(filtered_data1)
  
  ## ---------- mean resistance ----------
  mean_data1 <- dplyr::group_by(filtered_data1, cell, treat)
  
  mean_data1 <- dplyr::summarise(
    mean_data1,
    mean_value = mean(all_eff),
    .groups = "drop"
  )
  ## ---------- tidy summary table ----------
  summary_table <- dplyr::group_by(filtered_data1, cell, treat)
  
  summary_table <- dplyr::summarise(
    summary_table,
    mean = mean(all_eff),
    median = median(all_eff),
    sd = sd(all_eff),
    q25 = stats::quantile(all_eff, 0.25),
    q75 = stats::quantile(all_eff, 0.75),
    .groups = "drop"
  )
  
  summary_table$CDF <- cdf_data$CDF[
    match(
      paste(summary_table$cell, summary_table$treat),
      paste(cdf_data$cell, cdf_data$treat)
    )
  ]
  
  iqr_val <- summary_table$q75 - summary_table$q25
  summary_table$lower_bound <- summary_table$q25 - 1.5 * iqr_val
  summary_table$upper_bound <- summary_table$q75 + 1.5 * iqr_val
  
  summary_table$lower_whisker <- NA_real_
  summary_table$upper_whisker <- NA_real_
  
  for (i in seq_len(nrow(summary_table))) {
    x <- filtered_data1$all_eff[
      filtered_data1$cell == summary_table$cell[i] &
        filtered_data1$treat == summary_table$treat[i]
    ]
    
    x <- x[is.finite(x)]
    
    lower_candidates <- x[x >= summary_table$lower_bound[i]]
    upper_candidates <- x[x <= summary_table$upper_bound[i]]
    
    summary_table$lower_whisker[i] <- min(lower_candidates)
    summary_table$upper_whisker[i] <- max(upper_candidates)
  }
  
  summary_table$lower_bound <- NULL
  summary_table$upper_bound <- NULL
  
  ## ---------- plot ----------
  treatment_resistance <- ggplot2::ggplot(
    filtered_data1,
    ggplot2::aes(
      x = cell,
      y = all_eff,
      fill = cell
    )
  ) +
    ggplot2::geom_violin(
      draw_quantiles = c(0.25, 0.5, 0.75),
      trim = FALSE
    ) +
    ggplot2::facet_wrap(~ treat) +
    ggplot2::geom_hline(
      yintercept = 0,
      linetype = "dashed",
      colour = "blue",
      linewidth = 1.5
    ) +
    ggplot2::labs(
      x = "Cell line",
      y = "Treatment resistance (logₑ)",
      fill = "Cell line"
    ) +
    ggplot2::theme(
      axis.text.x = ggplot2::element_text(
        face = "bold",
        size = 15,
        angle = 45,
        hjust = 1
      ),
      axis.text.y = ggplot2::element_text(face = "bold", size = 15),
      axis.title.x = ggplot2::element_text(face = "bold", size = 18),
      axis.title.y = ggplot2::element_text(face = "bold", size = 18),
      strip.text = ggplot2::element_text(face = "bold", size = 18),
      plot.margin = ggplot2::margin(20, 20, 40, 40),
      legend.title = ggplot2::element_text(size = 20),
      legend.text = ggplot2::element_text(size = 15)
    )
  
  ## ---------- return ----------
  out <-list(
    treatment_resistance = treatment_resistance,
    summary_table = summary_table,
    type = "QTR"
  )
  class(out) <- "barmixR_result"
  out
}
